language: php
php:
- 7.2
before_script:
- printf "\n" | pecl install imagick
- phpenv config-rm xdebug.ini
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
- php artisan key:generate
- php artisan migrate:fresh --seed
before_install:
- mysql -u root -e 'DROP DATABASE IF EXISTS travis;'
- mysql -u root -e 'CREATE DATABASE IF NOT EXISTS travis;'
script:
- phpunit
services:
- mysql
cache:
  directories:
  - node_modules
  - vendor
env:
  matrix:
  - TRAVIS_NODE_VERSION="4"
  global:
  - secure: geKBBmtiyr8i3g84+ORiWKW8j58DgoEAg2y588G69mMxh7iBQyNmlv5pFIB7Q2eH7o/oUO0ixUgvEGdHssVTFmAksBAEPe1SgIYL7HQ+YGoGORnxUa/yc4ISkYTRQzQ716Ncafkqdtj6aI8rk6peCmNB4dTI0W45t8OaAZDUhMdEf8qN1z5ar47rgithAYK3cnqLkUdXmJ9ab/ZlMcmyiIOt7leZSfuLQyp7RWFpL9+9G2n/sLKOVdvHQTfiu5fGIxbdE9/yYSUsXHtMTRbWEMAeTnDMwB+Lv4mpm/hbuPUaRuW0m3KEAUxVLayjCoptrCYBqtV8RlF+6EO1AxjQQOaVAuW9y1V8WQa/sf4xnUl+1c3v0MO2pV6oQ2qzUzYDSUyUbxS0AO6R9Gi6s011ygaOVJaMAilYX7xox3/PLaHkiJ7ZEmTJasrFwXhml3ounjcjVTC0RrA98DOJA6yUOfavCfWnKwlpzYxEMTzeSFVpRVoUJyfe4eHebddKovjtmqVrRXwKj4Sh/1sF33c+iktNxjqW7Y/U7Z4SyI+AORCdoCPg3FKEByFzjHpV3Z3ogX4F57614SDGoP/0Q4tDcdOf+W09rECzLl/eUTC1FNuTcrnub/KjCfYqDFOi2J+zUorcINEjuZ1jmOmajt1DrUv+34eVsunLLOB7MW7SSgA=
  - secure: c6qU/9u9HL4RAkkgUGC/jR7JdUr5pmcUQG7Djzp8Hige5fpbVp+O/oObYbiAUWh8q6kk+Q4WeFEugCqu6bqmJasUXOxvtyEjffW25mccYuxV/q1jHrw6CaQ89qeKtaT4JhL2Yji9ngrHtpvp2MnYFSSQeFDDPdXW25kuYXxfiXK54eLpfOjP+w5Xy/UHRgUW+7nFdhIae3tH6wyNIcyAOGCObZT1V8b2RfniDEJFOLiKOcim6GWau0w8EuI7p8aV8376PYUnCFkvN+KyIH2g7io4SIUnsklhAAoUclTlcRsW2XaB/QGp8FX6Tv4NH+IBLV85MOBl+nUdJeDXe8jmWh3wticnEskxKJsA3zW3rMZiezCOzCG6CRXueaqKUlJQ16bzOfK7Fwp07CEJg+B5cxB4ocnmns7y4ilqsjvoIiURfX8SikbD05n3zuTT7huy+DEVHwdqhCBmV2A2gwnxjKmLg1iMD51I49y6BRohFJpGiQnpmTRkeohGGwWSlfrjxmojX/7H1p1YJjHaMkk9mYuvYf5Jd5k0z0Je2IUAj2iwiZHYP8cg3hYPx47Ui12x5YkEkUKTsnBj2YLi7RcJhxv48azwbfY1R5clRPP8eS0EK278m3gV93axMLeuGDTK4G+dWijMzUsI4Z0B6uw+sBkrtdjCvqb8vvCqKrmaMMU=
  - secure: elAfxvlLNShjRRRNgH71G7n/7lkfhETvLI0bxCXdRoNYajtEbj+xUO2N4l07f3KQxYtwDW+IrZ9cB2FXVeEpMgMkm/r2sJ3xD96PgfD3+TXszeqDb6THDjbg01Fk4SfTlT/DeR8/jT/RrMsdDkZQcQWxjbSBq0Dzxw98ONtxqRQa+8uLk8RMplxwOlFW24U48fNgEVIQ5VBhhLph0ZO9L+oJJflVy9h2prrGwM65U38wI6+EBZ8DO9n/GK5vZIPuiQnx7dDrYQg7mWZ+bg3flVFnz0nSz+IpOF4McoUL68mQiYF5PPx/nq+OONlYNCxKkw/NvrkUaaSOHacGuzV8JVQKfYp5DXtlCmWg7Hu1BGuTVCbQ2YMMPbvXJDmoOQjo4idYURybOxD7BilfehDgccPuQmQYS0/c4j1lmEJsvOirHreUZPnLlUJ1v5xgEAg4T/NCXM8eR6ZVJYKLwCyhLX+0o04jbXcqSnkTEjpTa5TqYfysxwzpcEDypGu1wxgBzYgtowT45UWlhjrgH/EaZ5pXm+tWOWxG45YN4dJgcfP/94y29JXp+JV8dkAQB193dVUi0YN0hQU1VV7mXqexxI5NNgdbvfV3pvcOF0lJgB5DRELrkoTSBarOHDQMVsVw6J+y4DdsuAIxiyZFzc2WFmgxAxCdaaA2aZOJR9feya0=
  - secure: ANiQoqtjhqoKiEMl01L98BrWBIZOrrDSGdRpUI74+sCt90IgoPURR18OOEzHY/UxKcJ1wzQurSo36Se99Pkobue3H4UM0DrgEjxDVoRJeMJk/VysU8KZj5+mQcKXf+ILwbzCrhMtLdR2RD7pnWi1CM0qUu8If/wDprrWrS+5B7qIrPddB0uUfnvw/pxW/m8kxSD8A+60IGZo5xPsd+GJTpn5Y9TKodDKrM+knMPMND8Zp6UuUB+XZgqgdvVtb1Yfh3BvFIdju++GMp/ejJcOyB5Z+jz5TbmEE5DjKfNbNok43jhN/b3yTPgmO+bwUKbQvnojL5NiLjc6q/iSP1VJqQJOo47ffnv78v4DsVKJHI5IylpSZM2785fBnmf6KeHgXX+qitV7K8SUiIp3DPoK4wTzIXVhIunrREmt2H5uQnJ4LP3IZ7wbTOzC1X9ysLdj64DMFwHWdXJfENQxD4zryewuv3t8grcbj1CEl4++9G8Q9i0hqjcdAHjRrFuErCsoaw1odM1pNG3JoqQ9d8Vw9Bzau3yMXJNHasxruVAKpKl6bti5jaHq4SMRkYsRvu1JMPMydnR8mRt4VVs/6Qg3fUgKv7cX4yOwRIB6cPnueWGk7i4wzikKD1WYbrh5vVOU3ZXNGqlWxaYErdEhrzgIudXubJidAeI9akAVGvWgJfI=
install:
#- echo "MAIL_USERNAME=${MAIL_USERNAME}" >> .env
#- echo "MAIL_PASSWORD=${MAIL_PASSWORD}" >> .env
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "${AWS_ACCESS_KEY_ID}"
  secret_access_key:
    secure: "${AWS_SECRET_ACCESS_KEY}"
  region: us-east-2
  app: SandBox
  env: flipbook-dev-env
  bucket_name: "elasticbeanstalk-us-east-2-006536376604"
