language: php

php:
  #- 5.6
  #- 7.0
  #- 7.1
  - 7.2

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed
  #- php artisan db:seed
  #- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  #- npm install --global gulp-cli
  #- npm install
  #- gulp --production

before_install:
  - mysql -u root -e 'DROP DATABASE IF EXISTS allanbarcelos;'
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS allanbarcelos;'
  #- mysql -u root -e 'SHOW DATABASES;'

script:
  #- phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
  - phpunit

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

env:
  - TRAVIS_NODE_VERSION="4"
