language: php
php:
- 7.2
before_script:
- phpenv config-rm xdebug.ini
- cp .env.travis .env
- composer self-update
- composer install --no-interaction
- php artisan key:generate
- php artisan migrate --seed
before_install:
- mysql -u root -e 'DROP DATABASE IF EXISTS travis;'
- mysql -u root -e 'CREATE DATABASE IF NOT EXISTS travis;'
script:
- phpunit
services:
- mysql
cache:
  directories:
  - node_modules
  - vendor
env:
  matrix:
  - TRAVIS_NODE_VERSION="4"
  global:
  - secure: b7a2GchujTHCCM12ek+zq+ExeyucZtCOX2lpyS9UqVCakENj1b7Xntq1lR5FvHeFyZDYJtjyofoinr82uj1mbpvWbYkg9nrXzfwyWkPRs/h0zNcINvukBSCqbx7mVQWwCKv4ufrKQTUG6TfjpXOmhan9/Df0sxtx4SgG1dKeg/VrjVPnZEusjbDGAhakV/AMYR2xF1Bw8IAEbEv9k/am6/o3x0HVJeQmd7xtctWYNiJ6AQvu+OxEjwrslFBmSgTVxvfmj9GxBCp1M494w7duqVcV0c++each6YFXC6oJ8C1XE7tApt1oHuKp8hzxirPrdSZYG2NpS6j1kMlpskSziHSaIC0anEjfZTcOzEQNqrxeOt8EBU0vG68Mc2OqCUXUpVDU3dVgbhEEUO2Wb7/IAFaQjqHX3nf0l+I2MucT5SMXggUAKCgENLbHKgDNN7HiNVIkkBThm0tiAG4w6ukv12u7t4Jodb42hJvNOFULC2Z5P9A6fOUC7Ck+OJWrjmU+Vf54Ts1p01jYrkVJDmr/YMLFwiTQGJ1ODMWtyM+YZFSa19qyVdwJrV+tuBmMTTaEphAY9WdG8Hh6vL2A6PsCpInhRb8E3XPywOy3edaBO1B+n76xjSmh2gdlhPneEedzgPVzcXmT7t7U7NenZIsWvJLf20UtWdutqb3SISCuEIk=
  - secure: EE4pKjj+wrJ3BDpqAhtScSpN79tpWJQ7mShCA8ku7DXlLtdxUlEIpYzXPruM2t692fPfgEnRTHVdWlwKrq6Ycnrxa+IOObnqxA5qzIGvvWxsWB7Mvr0OJJKoYtQtj/gGRys0+sN1nb7syt7RDXiGdrMhhCtUfHb0a9Zv4t82jpZERdjjBhP3VAeYx2KAyfhmKzF3PMCI/5y1AaCzxOG7GXH6VsQbZ+UuE843UfqtWX3pT/TlXv75D33z8d8h3pD1TRVC7GV4rkfhmNuN4Wj4zYHXrj4xqE/rWDZOBWGTY9nVN6I2b3zYRhgcmWxSoByQXAgapBAfmoKEu4rsBiPl4ArqjYMOIJsIufxObOG6P1tn0iNB571vGek/zXK/WC7UrKgJd2ojogVgPEaCXewkMqRwURyp2etOnJpPPI7SQoX8yUNbSjRH45BotwilB5ZJ+tL3gcs4NVODEkRqk3bHlZrvW8VLSMSaf/jHJwrH9zo52NNW3aRfofy4VofhCS57gmxRl1vE+sOnQ66VQ/91Z+KfqdKWwDqNr0tZ1xM0bbXfrStBCLoUKRk1lw0Rrj2uoFxAOlbSmRX6u4N81Ges3MeVYAZ1HxCEYsbWmeDWjCWr3KHr97zVhhxg2Ga8XKyCmrx9EjZnJvtDwbPZDyJc2mOtw8loeFF162N85eaZ+fg=
  - secure: pwFyCyZykpvltwETOOhybGnOJvGZGptb0rHaEG5lpXUBYw43V5nP57GwZ1frIk3nc8u3iE+8kIv2Y4NofSfX1am1vWMDEpcSOQgBVJKMDZsFJcPFHLx8bapQLikWQz9cEv9jU7EqlGIPGwg7AIXVerFBYQAzQSqTYOtmvKR3BEIkM3M0u4byF/cE9KfeCAozJl/hbWIhQ2mlWDqlvA2xHT3xz0nzFMFK8Zuk98MfLISeOrgwEt0Np1wtkVUACY+8yFvbCdwmDHQEJl1fxCHQ2kkjeyEVge2012WSD/BSnJ4+tgCCH5W1+L1AxSdw42IEWQoY//F7EUwV/xwyxeqjqH73Ln2L6n/orz7HP8tsM8I5YPro1tuhD7n8E8MA22pzd4jFu5EG+hPh1kwQL7+shoOcjKYI7rS03heZRTxhMOCDfCc4PIQf+ZQMjGsoifdzv35J0T93KxJf8peBWUJ1SF+T2JxMFxEaCzRS8fIE2mW9IXtrHtPrvj81jDkq/2yfhH9PKG/1CK/KtC5bLZVjk7/RSHwWofAmBCU6pXkAX04o/ag0JcNFcjEwvYwFVENyl2fUyOil79B6Antifzfn0VrJ5aD3ivcWWWvI3EBmyJjNvzIRLIU/mvteZ1hdeqpfSZWiqI1S9m1IpdtH6QzzI4cEFRALmQ52LjXizue0XvY=
  - secure: MVoFRL9yVU08/QdhhwphX0KcGfrLk21ibahBhi8zpdknlMEQFPltfKZxpdcd1gw9IGeNBG6Puh2rr+swKPhBjIPF9JcRcrC0RnMTJihp01ATDNpQ2k6W1/8/WhXeUCKo6s6lkcCGR+xnUrLluL+PNnWDChLFzWIqdn+QOmo5LnhQIriJdTFSqO+JRMUay8aW/CEwwF7+D5V6tkH3tk0ULJuu633RCzbVA5ljquC2KYJ84Bn3lUWXpR7Vbd8A5nVGy7CfYN4544Y72p1sa0AlXigQE5H0NSxhOncQip5BbERBQIcb6zlqaCy/sg+sXrYRr/7XVZ6+C9kltHaDwHXvlU4CaoedJKk/Ufsf00LcUBp/VENIwrHxC7OnP80HPZyzr42OIIkcjYU26+ThNiB/fzU1FOjhVdut2Fgdcp8tOap5fN7AnfjktElSNCy8jlucN8DT2vBoEqUe/a7L4jDSSn03YH50RirO+E+Ym8Q+7LTelMUMKER566iEByIB83XBd/GBYuV1EzsFffbrrk2Lw1V/o5zgBFRuQ7PFeQomk0cqXKLWPhvZy9OXDnkWWdnHxPi1gwNII+qc/i6BdIUJ1cMy9IWJywp/9CxvHIGEw2G9Qq2dUD/Xi6AQnEl0AIf9YJbCa7KPZRbruu6p65NwXp19yKq1EpTStfn0yjql/R0=
  - secure: DGfbf+4nFGnFQWdvbcEusS0xPnOy6cPhx+NVOwi8yZPSyO4j5zbm09c92s2xF6aG//VEuLAtWtGfQDy+v7TwsM26RpNiwJFU66K7TXglMxQT1qmCaNlp2QGEsVgshIMJFwioVXCtqa9NvWhXf+50+T5B3vy2k21UPnY9zOpyo6taVXsmBGeL5zs6rE7mYLiFFVMfcbbrdQknN0IU0rhNWIrFwKX73k+0twwZBSn0YxC3GAzByocHARH6Iu3UKFHedUCkosI29hun17y510FedwrxDJkVbCq7x5i/bn4LGQm4F7omanu0TWn4xPsbxDnGUuT2OIrzSt2hAN4YcAalK8KbMEF31LZlrVvU3J2MMEMfmccuHO/nhf810DGcDzuEFkGrCoPKttsNPJeTGaHKxpNQ+c9G/eAKbQ67PqPbxQyp5j5JwuscrxUy0RwJDoE8ff0XSTMZChHi4qk6jUVPm3FmhLtYHySeAwM+Nw46hnsnBq6jEkbyFCr82YGaKWyVCR4XnbDiYMcn8WCt8uTd/0sca5xsd/9VUTY97r/xzPcA1iH67yxLuf6b7SexZLSWXkXNubX+rCc/o096xcTOy2GHOS8FC3QN0/xqmHcvLKU5W3lpfShmcLdi2kfdSBwvanPGGLqfBPJNlXyDzRMUk6Cd88iBk0spK9Rba15E44I=
install:
- echo "MAIL_USERNAME=${MAIL_USERNAME}" >> .env
- echo "MAIL_PASSWORD=${MAIL_PASSWORD}" >> .env

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "${ACCESS_KEY_ID}"
  secret_access_key:
    secure: "${SECRET_ACCESS_KEY}"
  region: "us-east-2"
  app: "FlipBook"
  env: "flipbook-dev-env"
  bucket_name: "elasticbeanstalk-us-east-2-006536376604"
