version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/apache2/sites-available:/etc/apache2/sites-available
    ports:
      - "8080:80"
    networks:
      - laravel-net
    depends_on:
      - db
    command: >
      sh -c "composer install && php artisan migrate --seed && apache2-foreground"

  db:
    image: "mysql:8.0"
    container_name: laravel-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - laravel-net
    volumes:
      - ./.mysql-data:/var/lib/mysql

networks:
  laravel-net:
    driver: bridge
